name: Deploy to Firebase Functions on merge

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: Install Dependencies
        run: cd functions && yarn install --immutable --immutable-cache --check-cache
      - name: Build
        run: cd functions && yarn build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: cd functions && deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}